use starknet::ContractAddress;
use crate::types::{Subscription, SubscriptionStatus, BitFlowError};

#[starknet::interface]
pub trait ISubscriptionManager<TContractState> {
    /// Creates a new subscription plan
    /// @param price The price per billing period
    /// @param interval The billing interval in seconds
    /// @param max_subscribers Maximum number of allowed subscribers
    /// @param metadata Additional metadata for the plan
    /// @return plan_id The unique identifier for the created plan
    fn create_subscription_plan(
        ref self: TContractState,
        price: u256,
        interval: u64,
        max_subscribers: u32,
        metadata: felt252
    ) -> u256;
    
    /// Subscribes to a subscription plan
    /// @param plan_id The unique identifier of the plan
    /// @param duration The subscription duration in billing periods
    /// @param auto_renew Whether to automatically renew the subscription
    /// @return subscription_id The unique identifier for the subscription
    fn subscribe(
        ref self: TContractState,
        plan_id: u256,
        duration: u64,
        auto_renew: bool
    ) -> u256;
    
    /// Cancels an active subscription
    /// @param subscription_id The unique identifier of the subscription
    /// @return success True if cancellation was successful
    fn cancel_subscription(ref self: TContractState, subscription_id: u256) -> bool;
    
    /// Pauses an active subscription
    /// @param subscription_id The unique identifier of the subscription
    /// @return success True if pause was successful
    fn pause_subscription(ref self: TContractState, subscription_id: u256) -> bool;
    
    /// Resumes a paused subscription
    /// @param subscription_id The unique identifier of the subscription
    /// @return success True if resume was successful
    fn resume_subscription(ref self: TContractState, subscription_id: u256) -> bool;
    
    /// Renews a subscription for another period
    /// @param subscription_id The unique identifier of the subscription
    /// @param duration The renewal duration in billing periods
    /// @return success True if renewal was successful
    fn renew_subscription(ref self: TContractState, subscription_id: u256, duration: u64) -> bool;
    
    /// Gets subscription details
    /// @param subscription_id The unique identifier of the subscription
    /// @return subscription The Subscription struct with all details
    fn get_subscription(self: @TContractState, subscription_id: u256) -> Subscription;
    
    /// Gets the status of a subscription
    /// @param subscription_id The unique identifier of the subscription
    /// @return status The current subscription status
    fn get_subscription_status(self: @TContractState, subscription_id: u256) -> SubscriptionStatus;
    
    /// Gets all subscriptions for a specific user
    /// @param user The subscriber address
    /// @return subscription_ids Array of subscription IDs for the user
    fn get_user_subscriptions(self: @TContractState, user: ContractAddress) -> Array<u256>;
    
    /// Gets all subscriptions for a specific plan
    /// @param plan_id The unique identifier of the plan
    /// @return subscription_ids Array of subscription IDs for the plan
    fn get_plan_subscriptions(self: @TContractState, plan_id: u256) -> Array<u256>;
    
    /// Gets subscription plan details
    /// @param plan_id The unique identifier of the plan
    /// @return price The plan price
    /// @return interval The billing interval
    /// @return max_subscribers Maximum subscribers allowed
    /// @return current_subscribers Current number of subscribers
    fn get_subscription_plan(
        self: @TContractState,
        plan_id: u256
    ) -> (u256, u64, u32, u32);
    
    /// Updates subscription plan details (only by plan creator)
    /// @param plan_id The unique identifier of the plan
    /// @param new_price The new price per billing period
    /// @param new_max_subscribers New maximum number of subscribers
    /// @return success True if update was successful
    fn update_subscription_plan(
        ref self: TContractState,
        plan_id: u256,
        new_price: u256,
        new_max_subscribers: u32
    ) -> bool;
    
    /// Processes automatic renewals for expired subscriptions
    /// @param max_renewals Maximum number of renewals to process in one call
    /// @return renewed_count Number of subscriptions successfully renewed
    fn process_auto_renewals(ref self: TContractState, max_renewals: u32) -> u32;
    
    /// Gets revenue analytics for a subscription plan
    /// @param plan_id The unique identifier of the plan
    /// @return total_revenue Total revenue generated by the plan
    /// @return active_subscribers Current number of active subscribers
    /// @return total_subscribers Total number of subscribers (all time)
    fn get_plan_analytics(
        self: @TContractState,
        plan_id: u256
    ) -> (u256, u32, u32);
    
    /// Gets detailed subscription status breakdown for a plan
    /// @param plan_id The unique identifier of the plan
    /// @return active_count Number of active subscriptions
    /// @return paused_count Number of paused subscriptions
    /// @return cancelled_count Number of cancelled subscriptions
    /// @return expired_count Number of expired subscriptions
    fn get_plan_status_breakdown(
        self: @TContractState,
        plan_id: u256
    ) -> (u32, u32, u32, u32);
    
    /// Gets subscription renewal statistics for a plan
    /// @param plan_id The unique identifier of the plan
    /// @return total_renewals Total number of renewals processed
    /// @return auto_renewals Number of automatic renewals
    /// @return manual_renewals Number of manual renewals
    fn get_plan_renewal_stats(
        self: @TContractState,
        plan_id: u256
    ) -> (u32, u32, u32);
    
    /// Gets global platform analytics
    /// @return total_plans Total number of plans created
    /// @return total_subscriptions Total number of subscriptions
    /// @return total_revenue Total revenue across all plans
    /// @return active_subscriptions Total active subscriptions
    fn get_platform_analytics(
        self: @TContractState
    ) -> (u256, u256, u256, u32);
    
    /// Gets subscription churn rate for a plan
    /// @param plan_id The unique identifier of the plan
    /// @return churn_rate Percentage of subscribers who cancelled (scaled by 10000)
    fn get_plan_churn_rate(self: @TContractState, plan_id: u256) -> u32;
    
    /// Gets average subscription duration for a plan
    /// @param plan_id The unique identifier of the plan
    /// @return avg_duration Average duration in seconds
    fn get_plan_avg_duration(self: @TContractState, plan_id: u256) -> u64;
}